/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package me.littlepanda.dadbear.core.rpc;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface ClientMasterProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"ClientMasterProtocol\",\"namespace\":\"me.littlepanda.dadbear.core.rpc\",\"types\":[{\"type\":\"record\",\"name\":\"ServiceInfo\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"host\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"protocol\",\"type\":\"string\"},{\"name\":\"implement\",\"type\":\"string\"},{\"name\":\"port\",\"type\":[\"null\",\"int\"]},{\"name\":\"schedule\",\"type\":[\"null\",\"string\"]},{\"name\":\"distributeAlgo\",\"type\":[\"null\",\"string\"]},{\"name\":\"description\",\"type\":[\"null\",\"string\"]}]},{\"type\":\"record\",\"name\":\"SlaveInfo\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"ip\",\"type\":\"string\"},{\"name\":\"host\",\"type\":\"string\"},{\"name\":\"services\",\"type\":{\"type\":\"array\",\"items\":\"ServiceInfo\"},\"default\":[]}]}],\"messages\":{\"getServiceInfoByName\":{\"request\":[{\"name\":\"name\",\"type\":\"string\"}],\"response\":\"ServiceInfo\"},\"getAllServiceInfosByServiceName\":{\"request\":[{\"name\":\"name\",\"type\":\"string\"}],\"response\":{\"type\":\"array\",\"items\":\"ServiceInfo\"}},\"getServiceInfoByNameAndSlaveId\":{\"request\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"slave_id\",\"type\":\"string\"}],\"response\":\"ServiceInfo\"},\"getSlaves\":{\"request\":[],\"response\":{\"type\":\"array\",\"items\":\"SlaveInfo\"}},\"getSlaveById\":{\"request\":[{\"name\":\"slave_id\",\"type\":\"string\"}],\"response\":\"SlaveInfo\"}}}");
  me.littlepanda.dadbear.core.rpc.ServiceInfo getServiceInfoByName(java.lang.CharSequence name) throws org.apache.avro.AvroRemoteException;
  java.util.List<me.littlepanda.dadbear.core.rpc.ServiceInfo> getAllServiceInfosByServiceName(java.lang.CharSequence name) throws org.apache.avro.AvroRemoteException;
  me.littlepanda.dadbear.core.rpc.ServiceInfo getServiceInfoByNameAndSlaveId(java.lang.CharSequence name, java.lang.CharSequence slave_id) throws org.apache.avro.AvroRemoteException;
  java.util.List<me.littlepanda.dadbear.core.rpc.SlaveInfo> getSlaves() throws org.apache.avro.AvroRemoteException;
  me.littlepanda.dadbear.core.rpc.SlaveInfo getSlaveById(java.lang.CharSequence slave_id) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends ClientMasterProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = me.littlepanda.dadbear.core.rpc.ClientMasterProtocol.PROTOCOL;
    void getServiceInfoByName(java.lang.CharSequence name, org.apache.avro.ipc.Callback<me.littlepanda.dadbear.core.rpc.ServiceInfo> callback) throws java.io.IOException;
    void getAllServiceInfosByServiceName(java.lang.CharSequence name, org.apache.avro.ipc.Callback<java.util.List<me.littlepanda.dadbear.core.rpc.ServiceInfo>> callback) throws java.io.IOException;
    void getServiceInfoByNameAndSlaveId(java.lang.CharSequence name, java.lang.CharSequence slave_id, org.apache.avro.ipc.Callback<me.littlepanda.dadbear.core.rpc.ServiceInfo> callback) throws java.io.IOException;
    void getSlaves(org.apache.avro.ipc.Callback<java.util.List<me.littlepanda.dadbear.core.rpc.SlaveInfo>> callback) throws java.io.IOException;
    void getSlaveById(java.lang.CharSequence slave_id, org.apache.avro.ipc.Callback<me.littlepanda.dadbear.core.rpc.SlaveInfo> callback) throws java.io.IOException;
  }
}