/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package me.littlepanda.dadbear.core.rpc;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SlaveMasterProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SlaveMasterProtocol\",\"namespace\":\"me.littlepanda.dadbear.core.rpc\",\"types\":[],\"messages\":{\"sendHeartBeat\":{\"request\":[{\"name\":\"message\",\"type\":\"string\"}],\"response\":\"null\"}}}");
  java.lang.Void sendHeartBeat(java.lang.CharSequence message) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends SlaveMasterProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = me.littlepanda.dadbear.core.rpc.SlaveMasterProtocol.PROTOCOL;
    void sendHeartBeat(java.lang.CharSequence message, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}