/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package me.littlepanda.dadbear.core.config;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ConfigInitState { 
  INIT, OK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ConfigInitState\",\"namespace\":\"me.littlepanda.dadbear.core.config\",\"symbols\":[\"INIT\",\"OK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
